# Generated by Django 4.2.1 on 2023-05-29 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dss", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Response",
            new_name="Answer",
        ),
    ]
