# Generated by Django 4.2.1 on 2023-06-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dss", "0002_rename_response_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Criterium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "criterium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dss.criterium"
                    ),
                ),
                (
                    "study_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dss.studyprogram",
                    ),
                ),
            ],
        ),
    ]
