# Generated by Django 4.2.1 on 2023-06-04 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dss", "0003_criterium_score"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="score",
            unique_together={("criterium", "study_program")},
        ),
    ]
