# Generated by Django 4.2.1 on 2023-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dss", "0005_alter_score_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterium",
            name="short_description",
            field=models.CharField(default="todo", max_length=64),
            preserve_default=False,
        ),
    ]
