# Generated by Django 4.2.1 on 2023-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dss", "0006_criterium_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.CharField(max_length=128)),
                ("time", models.FloatField()),
            ],
        ),
    ]
