# Generated by Django 4.2.1 on 2023-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dss", "0007_timer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timer",
            name="system",
            field=models.IntegerField(),
        ),
    ]
